!define ThemeRed FF6F61
!define ThemeYellow FFDA29
!define ThemeBlue 98DDDE
!define ThemeLightGrey E9E9E9
!define ThemeGrey 595959
!define ThemeDarkGrey 454545
!define CommonBackgroundColor White
!define CommonBorderColor ThemeDarkGrey
!define CommonFontColor ThemeDarkGrey

skinparam BackgroundColor CommonBackgroundColor
skinparam ArrowColor CommonBorderColor
skinparam FontColor CommonFontColor
skinparam shadowing true
skinparam RoundCorner 7
skinparam defaulttextalignment center

hide <<external>> stereotype
hide <<important>> stereotype

skinparam useBetaStyle true
<style>
  element
  {
      FontColor CommonFontColor
      LineColor CommonBorderColor
  }

  package, person, artifact, component, cloud, frame, folder, file, rectangle, agent, partition, card, storage, usecase, stack, interface, entity, boundary, control, note, activityDiamond, activity, class, object, map, state, sequenceDivider, sequenceGroup, sequenceLifeLine, database, actor, participant, collections, queue
  {
      BackgroundColor CommonBackgroundColor
  }

  .important {
      BackgroundColor ThemeRed
      FontColor White
      LineThickness 1.5
  }

  .external {
     BackgroundColor ThemeLightGrey
     FontColor ThemeGrey
  }

  entity, boundary, control {
      BackgroundColor ThemeYellow
  }

  database {
      BackgroundColor ThemeBlue
  }

  note {
      BackgroundColor LightGreen
  }

  activity {
      StartColor CommonBorderColor
      EndColor CommonBorderColor
  }

  mindmapDiagram, wbsDiagram {
    node {
      BackgroundColor CommonBackgroundColor
    }
  }
</style>

'The following skinparams cannot be styled using new styling technique

'Required to syle the border of objects
skinparam object {
    BorderColor CommonBorderColor
}

'Required to style the short form diamond <>
skinparam class {
    BorderColor CommonBorderColor
    BackgroundColor CommonBackgroundColor
}